add incat diff step
git-svn-id: file:///localdisk/subversion/inca/trunk/devel/projects/updateincat@14537 7dba3f4a-8be6-0310-8b3b-b4fec25ea7f3

diff --git a/bin/commitIncat b/bin/commitIncat
--- a/bin/commitIncat
+++ b/bin/commitIncat
@@ -1,17 +1,67 @@
 #!/bin/sh
 
 AGENT="localhost:6323"
+WRAP_CONFIG_LIBS="lib/log4j-1.2.15.jar:lib/xbean-2.4.jar:lib/incaXmlBeans.jar:lib/inca-common.jar:lib/incat.jar"
+CLIENT_LIBS="../teragrid/etc:lib/log4j-1.2.15.jar:lib/bcprov-jdk14-131.jar:lib/saxon9.jar:lib/saxon9-dom.jar:lib/xbean-2.4.jar:lib/xbean_xpath-2.4.jar:lib/inca-common.jar"
 
-if [ "$1" = "" ]; then
-  echo "Please specify incat file" >&2
+FORCE=no
+USAGE="Usage: $0 [-f] <new incat file> <old incat file>"
+
+while getopts fh o; do  
+case "$o" in
+  f)  FORCE=yes;;
+  \?)  print >&2 $USAGE
+    exit 1;;
+  esac
+done
+shift `expr $OPTIND - 1`
+
+if [ "$1" = "auto" ]; then
+  newIncatFile=incat-auto-new.xml
+  oldIncatFile=incat-auto.xml
+else
+  if [ "$1" = "" ]; then
+    echo "Please specify new incat file" >&2
+    echo $USAGE
+    exit 1
+  fi
+  
+  if [ "$2" = "" ]; then
+    echo "Please specify old incat file" >&2
+    echo $USAGE
+    exit 1
+  fi
+  newIncatFile=$1
+  oldIncatFile=$2
+fi
+
+if [ ! -f $newIncatFile ]; then
+  echo "Missing $newIncatFile" >&2
+  echo $USAGE
   exit 1
 fi
 
-incatFile=$1
+if [ ! -f $oldIncatFile ]; then
+  echo "Missing $oldIncatFile" >&2
+  echo $USAGE
+  exit 1
+fi
 
-echo "Ready to commit changes in $incatFile to $AGENT...press enter to continue"
-read
+echo "Creating incat file for commit"
+java -cp $WRAP_CONFIG_LIBS edu.sdsc.inca.WrapConfig $newIncatFile $oldIncatFile incat-diff.xml
+echo "------------"
+cat incat-diff.xml
+echo "------------"
 
-cmd="java -cp ../teragrid/etc:lib/log4j-1.2.15.jar:../teragrid/lib/bcprov-jdk14-131.jar:lib/saxon9.jar:lib/saxon9-dom.jar:lib/xbean-2.4.jar:lib/xbean_xpath-2.4.jar:lib/inca-common.jar  edu.sdsc.inca.AgentClient -f $incatFile -A $AGENT -P stdin:password: -c incatcert.pem -k incatkey.pem -t trusted"
-echo $cmd
-$cmd
+if [ "$FORCE" = "yes" ]; then
+  echo "Ready to commit changes in inca-diff.xml to $AGENT...press enter to confirm"
+  read
+  
+  cmd="java -cp $CLIENT_LIBS edu.sdsc.inca.AgentClient -f incat-diff.xml -A $AGENT -P stdin:password: -c incatcert.pem -k incatkey.pem -t trusted"
+  echo $cmd
+  $cmd
+  
+  echo "Moving $newIncatFile to $oldIncatFile";
+  mv $newIncatFile $oldIncatFile
+  echo "done"
+fi
