modified documentation building so that web service documents are automatically generated from the wsdl file
git-svn-id: file:///localdisk/subversion/inca/trunk/pubs@13207 7dba3f4a-8be6-0310-8b3b-b4fec25ea7f3

diff --git a/pubs/docs/configure b/pubs/docs/configure
--- a/pubs/docs/configure
+++ b/pubs/docs/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="Makefile.inc.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE DB2HTML DB2PDF DB2RTF DSSSL_PATH STYLE_OPTION HTML_MODE PDF_MODE TOP_DIR TARGETS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE DB2HTML DB2PDF DB2RTF XSLTPROC DSSSL_PATH STYLE_OPTION HTML_MODE PDF_MODE TOP_DIR TARGETS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1453,6 +1453,52 @@ else
 	#OUTPUT='-o $*'
 fi
 
+# Extract the first word of "xsltproc", so it can be a program name with args.
+set dummy xsltproc; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XSLTPROC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XSLTPROC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XSLTPROC="$XSLTPROC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in no
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XSLTPROC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_XSLTPROC" && ac_cv_path_XSLTPROC="xsltproc"
+  ;;
+esac
+fi
+XSLTPROC=$ac_cv_path_XSLTPROC
+
+if test -n "$XSLTPROC"; then
+  echo "$as_me:$LINENO: result: $XSLTPROC" >&5
+echo "${ECHO_T}$XSLTPROC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "$XSLTPROC" = "no"; then
+	{ { echo "$as_me:$LINENO: error: Unable to locate xsltproc" >&5
+echo "$as_me: error: Unable to locate xsltproc" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 DOCLIST=`ls src | grep .sgml`
 TARGETS=`echo ${DOCLIST} | sed 's/\.sgml//g' | sed 's/\entities//g'`
 
@@ -2107,6 +2153,7 @@ s,@SET_MAKE@,$SET_MAKE,;t t
 s,@DB2HTML@,$DB2HTML,;t t
 s,@DB2PDF@,$DB2PDF,;t t
 s,@DB2RTF@,$DB2RTF,;t t
+s,@XSLTPROC@,$XSLTPROC,;t t
 s,@DSSSL_PATH@,$DSSSL_PATH,;t t
 s,@STYLE_OPTION@,$STYLE_OPTION,;t t
 s,@HTML_MODE@,$HTML_MODE,;t t
